### ISSUE TITLE
レビュー用issue

### ISSUE THREAD

**Issue by kei0299** [kei0299/myapp#35]
■Webアプリの概要
このアプリは、失業者やフリーターが生活費を効率的に管理し、今後の生活資金を簡単に予測できるツールです。
貯金額と月々の支出を入力するだけで、どれくらいの期間生活を維持できるかをリアルタイムで確認でき、勤務先の登録やシフト入力によって収入も自動反映されます。
また、Googleカレンダーと連携し、収支管理をカレンダー上で可視化できるため、予定と合わせた総合的な家計管理が可能です。
貯金の減少に伴うアラート機能や支出予算の通知機能もあり、生活の不安を軽減し、計画的な家計運営をサポートします。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20 - 25時間

■ProjectsのURL
https://github.com/users/kei0299/projects/3/views/1

■MVPリリースまで
- [ ] 環境構築
- [ ] render、vercelにデプロイ
- [ ] TOPページ作成
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ホーム画面
- [ ] 生存期間設定画面
- [ ] 予算設定画面
- [ ] カレンダー機能
- [ ] 収支入力

■MVP後
- [ ] レポート画面作成(chart.js使用)
  - [ ] 円グラフ
  - [ ] プログレスバー
  - [ ] 折れ線グラフ
- [ ] Googleログイン
- [ ] Googleカレンダー連携
- [ ] 通知機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] 退会処理
- [ ] 勤務先登録
- [ ] シフト登録
- [ ] プロフィール画面
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] ファビコン
- [ ] レスポンシブ対応
- [ ] お問い合わせ画面

■MVPレビュー依頼予定日
予定日：2024年 11月 14日

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
概ね良いかと思います、LGTMです！

**Comment by kei0299** [comment]
レビューありがとうございます！
引き続きよろしくお願いします。
